# Description: SecretStore configuration for Azure Key Vault with Service Principal authentication

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-secretstore
  namespace: ${ESO_TEST_NAMESPACE}
  labels:
    app: external-secrets-examples
    component: secretstore
    example: secretstore
spec:
  provider:
    azurekv:
      authSecretRef:
        clientId:
          name: azure-keyvault-sp
          key: client-id
        clientSecret:
          name: azure-keyvault-sp
          key: client-secret
      tenantId: "${AZURE_TENANT_ID}"
      vaultUrl: "https://${ACTUAL_KEYVAULT_NAME}.vault.azure.net"
      type: AzureKV
      environmentType: PublicCloud
---
# Service Principal secret referenced by SecretStore
apiVersion: v1
kind: Secret
metadata:
  name: azure-keyvault-sp
  namespace: ${ESO_TEST_NAMESPACE}
  labels:
    app: external-secrets-examples
    component: secret
type: Opaque
data:
  client-id: ${SERVICE_PRINCIPAL_CLIENT_ID_B64}
  client-secret: ${SERVICE_PRINCIPAL_CLIENT_SECRET_B64}

