apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-operator
  labels:
    kubernetes.io/metadata.name: external-secrets-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: external-secrets-operatorgroup
  namespace: external-secrets-operator
spec:
  targetNamespaces: []
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-external-secrets-operator
  namespace: external-secrets-operator
  labels:
    operators.coreos.com/openshift-external-secrets-operator.external-secrets-operator: ""
spec:
  channel: tech-preview-v0.1
  installPlanApproval: Automatic
  name: openshift-external-secrets-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: external-secrets-operator.v0.1.0
