# SecretProviderClass Template
# This template uses Service Principal authentication (only supported method)

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ${SPC_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: secrets-store-examples
    component: secretproviderclass
    example: ${EXAMPLE_TYPE}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    useWorkloadIdentity: "false"
    keyvaultName: "${KEYVAULT_NAME}"
    tenantId: "${AZURE_TENANT_ID}"
    clientId: "${SERVICE_PRINCIPAL_CLIENT_ID}"
    objects: |
      array:
${SECRET_OBJECTS}
${SECRET_OBJECTS_SYNC}
  ${NODE_PUBLISH_SECRET_REF}